const TransactionsActionsTypes = {
  ADD_TRANSACTION_START: "ADD_TRANSACTION_START",
  ADD_TRANSACTION_SUCCESS: "ADD_TRANSACTION_SUCCESS",
  ADD_TRANSACTION_FAILURE: "ADD_TRANSACTION_FAILURE",
  ADD_TRANSACTION_RESTART: "ADD_TRANSACTION_RESTART",
  DELETE_TRANSACTION_START: "DELETE_TRANSACTION_START",
  DELETE_TRANSACTION_SUCCESS: "DELETE_TRANSACTION_SUCCESS",
  DELETE_TRANSACTION_FAILURE: "DELETE_TRANSACTION_FAILURE",
  DELETE_TRANSACTION_RESTART: "DELETE_TRANSACTION_RESTART",
  UPDATE_TRANSACTION_START: "UPDATE_TRANSACTION_START",
  UPDATE_TRANSACTION_SUCCESS: "UPDATE_TRANSACTION_SUCCESS",
  UPDATE_TRANSACTION_FAILURE: "UPDATE_TRANSACTION_FAILURE",
  UPDATE_TRANSACTION_RESTART: "UPDATE_TRANSACTION_RESTART",
  UPDATE_TRANSACTION_COUNT_START: "UPDATE_TRANSACTION_COUNT_START",
  UPDATE_TRANSACTION_COUNT_SUCCESS: "UPDATE_TRANSACTION_COUNT_SUCCESS",
  UPDATE_TRANSACTION_COUNT_FAILURE: "UPDATE_TRANSACTION_COUNT_FAILURE",
  UPDATE_TRANSACTION_COUNT_RESTART: "UPDATE_TRANSACTION_COUNT_RESTART",
  RETRIEVE_TRANSACTIONS_START: "RETRIEVE_TRANSACTIONS_START",
  RETRIEVE_TRANSACTIONS_SUCCESS: "RETRIEVE_TRANSACTIONS_SUCCESS",
  RETRIEVE_TRANSACTIONS_FAILURE: "RETRIEVE_TRANSACTIONS_FAILURE",
};

export default TransactionsActionsTypes;
